### ISSUE TITLE
Failed to establish a new Connection 

### ISSUE THREAD

**Issue by FakeSteveJobs99** [Naategh/dom-red#1]
it Doesn't working on Kali, i have installed all requirements with PIP but urllib3. connection.HTTPConnection object at 0xxxxx >: Failed to establish a new Connection always Appear

**Comment by Naategh** [comment]
Did you use `-i` flag?
If you can please comment exactly what you got.

**Comment by FakeSteveJobs99** [comment]
Hi, thanks, sure -i flag is attch, may you can take a look for Error capture
![Error_dom-red](https://user-images.githubusercontent.com/60311226/73133807-714aff80-4060-11ea-9e9c-b6f2caa55303.JPG)

**Comment by Naategh** [comment]
`Name or service not known` occurs when you try to fetch a domain name that doesn't exist (or potentially if your DNS server is having problems), I suggest to open that special URL via browser to know what's wrong.
Anyway, I added another exception block to handle this type of error, So the script now show that URL caused an error and will continue its work.
Just download the script and try again.
Feel free to comment again if you have problem yet or close the issue.

**Comment by FakeSteveJobs99** [comment]
Hi Dude, Thanks for Super Fast Respon!
i think like that as well , the logic should skip the link when found a broken or dead link, now it's Working, Super cool tool, thank you!

**Comment by Naategh** [comment]
You're welcome.
