### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by catekuser** [Naategh/dom-red#2]
Hi,
I get the following error:

res = open(output, "a+")
TypeError: coercing to Unicode: need string or buffer, NoneType found

Not sure how to fix.

**Comment by Naategh** [comment]
Please share the command you tried.

**Comment by catekuser** [comment]
python dom-red.py -d domains.txt -p payloads.list

domains are in the following format: example.com

**Comment by Naategh** [comment]
Thanks for reporting this, I fixed the issue.

**Comment by catekuser** [comment]
To update the repo: git pull https://github.com/Naategh/dom-red.git
Run the same command: python dom-red.py -d /root/domains.txt -p payloads.list
Error:
Traceback (most recent call last):
  File "dom-red.py", line 93, in <module>
    res = open(output, "a+")
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by Naategh** [comment]
Please remove project directory, Then download it with git clone and test again.
This should work.

**Comment by catekuser** [comment]
now it works...thank you.
